import type { Metadata } from "next";
import { Changa_One, Geist, Dynalight, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const changaOne = Changa_One({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-changa",
});

const dynalight = Dynalight({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dynalight",
});

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${changaOne.variable} ${geistSans.variable} ${dynalight.variable} ${poppins.variable}`}>
      <body className="bg-[radial-gradient(ellipse_at_center,_#2a2a2a_0%,_#1f1f1f_45%,_#141414_70%,_#0b0b0b_100%)] min-h-screen font-sans">
        {children}
      </body>
    </html>
  );
}
