import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Changa_One } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const changaOne = Changa_One({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-changa",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${changaOne.variable} ${geistSans.variable}`}>
      <body className="min-h-screen bg-black font-sans">
        <Header />
        {children}
      </body>
    </html>
  );
}
